version: "3.9"

services:
  db:
    build: .
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: kgpc
    volumes:
      - db_data:/var/lib/postgresql/data
      - /home/ec2-user/logs/postgresql:/var/log/postgresql
      - /home/ec2-user/postgres_conf/postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bdd_nginx_app-network
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/ec2-user/logs/nginx:/var/log/nginx
    networks:
      - bdd_nginx_app-network

networks:
  bdd_nginx_app-network:
    external: true

volumes:
  db_data: